In [292]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [293]:
df = pd.read_csv('data/Total_csv.csv',sep='\t')

In [294]:
# best feature 추출
best_df = df[['Question_count','First_ratio','Second_ratio','Tag_count','pos_ratio',
 'neg_ratio','subjectivity','polarity','senti_diffs_per_ref','Sticker_count','Text_len','Count_space_mistake',
   'effort_ratio','effort_img_ratio','Left','Center','Right','Justify',
   'img img img img img','img img img img text','img img img text img','img img text img img','img img text img text',
 'img text img img img','img text img img text','img text img text img','text img img img img','text img img img text',
 'text img img text img','text img text img img','text img text img text','Credibility']]

print ("before: ", best_df.shape)
best_df = best_df.dropna()
print ("after: ", best_df.shape)

before:  (16304, 32)
after:  (16213, 32)

In [295]:
from sklearn.utils import shuffle
best_df = shuffle(best_df)

In [296]:
Credibility = best_df[best_df['Credibility']==1]
Non_credibility = best_df[best_df['Credibility']==0]

# Credibility data shuffle

In [297]:
from sklearn.utils import shuffle
Credibility = shuffle(Credibility)
Non_credibility = shuffle(Non_credibility)
print ("credible: ", Credibility.shape)
print ("non: ",Non_credibility.shape)

train_credibility = Credibility[:6000]
train_non_credibility = Non_credibility[:6000]
print ("credible: ", train_credibility.shape)
print ("non: ", train_non_credibility.shape)

test_cred = Credibility[6000:6289]
test_non_cred = Non_credibility[6000:6289]
print ("credible: ", test_cred.shape)
print ("non: ", test_non_cred.shape)

df_test_total = pd.concat([test_cred, test_non_cred], axis = 0)
print ("shape: ", df_test_total.shape)
df_test_total.sample(10)

credible:  (9924, 32)
non:  (6289, 32)
credible:  (6000, 32)
non:  (6000, 32)
credible:  (289, 32)
non:  (289, 32)
shape:  (578, 32)

,Question_count,First_ratio,Second_ratio,Tag_count,pos_ratio,neg_ratio,subjectivity,polarity,senti_diffs_per_ref,Sticker_count,...,img img text img text,img text img img img,img text img img text,img text img text img,text img img img img,text img img img text,text img img text img,text img text img img,text img text img text,Credibility
4441,3,0.005489,0.0,7,0.026515,0.106061,0.132576,6.000000e-01,-0.079545,0.0,...,0.000000,0.0,0.000000,0.000000,0.00000,0.0,0.000000,0.000000,0.000000,1
2981,4,0.000867,0.0,0,0.032653,0.012245,0.044898,-4.545455e-01,0.020408,2.0,...,0.000000,0.0,0.000000,0.672368,0.00000,0.0,0.000000,0.000000,0.740217,0
8767,1,0.000000,0.0,4,0.076271,0.008475,0.084746,-8.000000e-01,0.067797,1.0,...,0.000000,0.0,0.000000,0.639871,0.00000,0.0,0.000000,0.000000,0.768482,0
1001,0,0.000000,0.0,1,0.000000,0.000000,0.000000,1.000000e-09,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.00000,0.0,0.000000,0.000000,0.000000,1
12298,1,0.002573,0.0,4,0.023346,0.027237,0.050584,7.692308e-02,-0.003891,0.0,...,0.393384,0.0,0.285388,0.595872,0.00000,0.0,0.402944,0.268527,0.417456,1
11550,2,0.001303,0.0,5,0.069252,0.041551,0.110803,-2.500000e-01,0.027701,1.0,...,0.190732,0.0,0.184494,0.693381,0.00000,0.0,0.195368,0.173594,0.616849,1
2931,0,0.000000,0.0,9,0.037815,0.021008,0.058824,-2.857143e-01,0.016807,0.0,...,0.000000,0.0,0.000000,0.658196,0.00000,0.0,0.000000,0.000000,0.752847,0
6258,2,0.002904,0.0,5,0.010050,0.025126,0.035176,4.285714e-01,-0.015075,0.0,...,0.000000,0.0,0.000000,0.658196,0.00000,0.0,0.000000,0.000000,0.752847,0
226,0,0.000000,0.0,3,0.026144,0.019608,0.045752,-1.428571e-01,0.006536,0.0,...,0.067529,0.0,0.000000,0.000000,0.09247,0.0,0.000000,0.000000,0.000000,1
4799,0,0.001934,0.0,0,0.094017,0.000000,0.094017,-1.000000e+00,0.094017,0.0,...,0.384829,0.0,0.372242,0.466330,0.00000,0.0,0.394181,0.350250,0.466717,0

In [298]:
df_train_total = pd.concat([train_credibility, train_non_credibility])
print ("shape: ", df_train_total.shape)
df_train_total.sample(10)

shape:  (12000, 32)

,Question_count,First_ratio,Second_ratio,Tag_count,pos_ratio,neg_ratio,subjectivity,polarity,senti_diffs_per_ref,Sticker_count,...,img img text img text,img text img img img,img text img img text,img text img text img,text img img img img,text img img img text,text img img text img,text img text img img,text img text img text,Credibility
4125,0,0.000000,0.0,0,0.000000,0.071429,0.071429,1.000000,-0.071429,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,1
3126,5,0.000000,0.0,0,0.036290,0.100806,0.137097,0.470588,-0.064516,0.0,...,0.000000,0.000000,0.000000,0.658196,0.0,0.000000,0.000000,0.000000,0.752847,1
11408,9,0.001848,0.0,2,0.049505,0.067327,0.116832,0.152542,-0.017822,0.0,...,0.000000,0.000000,0.000000,0.706814,0.0,0.000000,0.000000,0.000000,0.707400,1
7730,0,0.000000,0.0,6,0.040161,0.040161,0.080321,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.599682,0.0,0.000000,0.000000,0.000000,0.800238,0
8443,0,0.000000,0.0,2,0.030769,0.000000,0.030769,-1.000000,0.030769,3.0,...,0.148534,0.000000,0.143676,0.719966,0.0,0.000000,0.152144,0.135188,0.630492,0
2848,0,0.000688,0.0,5,0.033445,0.040134,0.073579,0.090909,-0.006689,0.0,...,0.301190,0.372031,0.291339,0.182489,0.0,0.442411,0.000000,0.548254,0.000000,0
14949,2,0.000752,0.0,6,0.043605,0.087209,0.130814,0.333333,-0.043605,0.0,...,0.252777,0.000000,0.244509,0.663675,0.0,0.000000,0.258920,0.230064,0.562037,1
8881,4,0.000000,0.0,2,0.051613,0.025806,0.077419,-0.333333,0.025806,0.0,...,0.000000,0.000000,0.000000,0.639871,0.0,0.000000,0.000000,0.000000,0.768482,0
2803,0,0.000000,0.0,0,0.023810,0.042857,0.066667,0.285714,-0.019048,0.0,...,0.000000,0.000000,0.000000,0.446917,0.0,0.000000,0.000000,0.000000,0.894575,1
11486,0,0.000000,0.0,3,0.000000,0.083333,0.083333,1.000000,-0.083333,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,1

In [299]:
from sklearn.utils import shuffle
df_train_total = shuffle(df_train_total)
df_test_total = shuffle(df_test_total)
df_train_total = df_train_total.reset_index(drop=True)
df_test_total = df_test_total.reset_index(drop=True)
df_train_total.head(10)

,Question_count,First_ratio,Second_ratio,Tag_count,pos_ratio,neg_ratio,subjectivity,polarity,senti_diffs_per_ref,Sticker_count,...,img img text img text,img text img img img,img text img img text,img text img text img,text img img img img,text img img img text,text img img text img,text img text img img,text img text img text,Credibility
0,0,0.000000,0.000000,6,0.040161,0.040161,0.080321,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.599682,0.000000,0.000000,0.000000,0.000000,0.800238,0
1,2,0.004769,0.000000,10,0.075540,0.035971,0.111511,-0.354839,0.039568,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1
2,1,0.000000,0.000000,2,0.039604,0.049505,0.089109,0.111111,-0.009901,0.0,...,0.000000,0.000000,0.000000,0.658196,0.000000,0.000000,0.000000,0.000000,0.752847,0
3,2,0.003704,0.000926,10,0.053140,0.028986,0.082126,-0.294118,0.024155,0.0,...,0.258172,0.318895,0.249728,0.156425,0.353524,0.000000,0.264447,0.234975,0.000000,0
4,2,0.011200,0.000000,10,0.106529,0.024055,0.130584,-0.631579,0.082474,0.0,...,0.000000,0.000000,0.000000,0.650481,0.000000,0.000000,0.000000,0.000000,0.759523,0
5,0,0.009412,0.000000,0,0.027304,0.044369,0.071672,0.238095,-0.017065,0.0,...,0.116351,0.287434,0.225091,0.375980,0.212431,0.113937,0.198631,0.141195,0.305737,1
6,0,0.000000,0.000000,6,0.047393,0.037915,0.085308,-0.111111,0.009479,0.0,...,0.000000,0.000000,0.000000,0.639871,0.000000,0.000000,0.000000,0.000000,0.768482,0
7,2,0.000000,0.000000,5,0.049724,0.016575,0.066298,-0.500000,0.033149,0.0,...,0.000000,0.000000,0.000000,0.658196,0.000000,0.000000,0.000000,0.000000,0.752847,0
8,4,0.000000,0.000000,2,0.025030,0.061979,0.087008,0.424658,-0.036949,0.0,...,0.000000,0.702806,0.000000,0.344741,0.000000,0.000000,0.000000,0.517855,0.345027,1
9,0,0.001292,0.000000,4,0.019737,0.013158,0.032895,-0.200000,0.006579,0.0,...,0.000000,0.169331,0.000000,0.664484,0.187719,0.000000,0.000000,0.124770,0.665035,0

# x, y selection

In [304]:
x = df_train_total.drop(columns=['Credibility'])
y = df_train_total[['Credibility']]
x.head(10)

,Question_count,First_ratio,Second_ratio,Tag_count,pos_ratio,neg_ratio,subjectivity,polarity,senti_diffs_per_ref,Sticker_count,...,img img text img img,img img text img text,img text img img img,img text img img text,img text img text img,text img img img img,text img img img text,text img img text img,text img text img img,text img text img text
0,0,0.000000,0.000000,6,0.040161,0.040161,0.080321,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.599682,0.000000,0.000000,0.000000,0.000000,0.800238
1,2,0.004769,0.000000,10,0.075540,0.035971,0.111511,-0.354839,0.039568,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,1,0.000000,0.000000,2,0.039604,0.049505,0.089109,0.111111,-0.009901,0.0,...,0.000000,0.000000,0.000000,0.000000,0.658196,0.000000,0.000000,0.000000,0.000000,0.752847
3,2,0.003704,0.000926,10,0.053140,0.028986,0.082126,-0.294118,0.024155,0.0,...,0.328315,0.258172,0.318895,0.249728,0.156425,0.353524,0.000000,0.264447,0.234975,0.000000
4,2,0.011200,0.000000,10,0.106529,0.024055,0.130584,-0.631579,0.082474,0.0,...,0.000000,0.000000,0.000000,0.000000,0.650481,0.000000,0.000000,0.000000,0.000000,0.759523
5,0,0.009412,0.000000,0,0.027304,0.044369,0.071672,0.238095,-0.017065,0.0,...,0.394566,0.116351,0.287434,0.225091,0.375980,0.212431,0.113937,0.198631,0.141195,0.305737
6,0,0.000000,0.000000,6,0.047393,0.037915,0.085308,-0.111111,0.009479,0.0,...,0.000000,0.000000,0.000000,0.000000,0.639871,0.000000,0.000000,0.000000,0.000000,0.768482
7,2,0.000000,0.000000,5,0.049724,0.016575,0.066298,-0.500000,0.033149,0.0,...,0.000000,0.000000,0.000000,0.000000,0.658196,0.000000,0.000000,0.000000,0.000000,0.752847
8,4,0.000000,0.000000,2,0.025030,0.061979,0.087008,0.424658,-0.036949,0.0,...,0.000000,0.000000,0.702806,0.000000,0.344741,0.000000,0.000000,0.000000,0.517855,0.345027
9,0,0.001292,0.000000,4,0.019737,0.013158,0.032895,-0.200000,0.006579,0.0,...,0.000000,0.000000,0.169331,0.000000,0.664484,0.187719,0.000000,0.000000,0.124770,0.665035

In [306]:
y.head(10)

   Credibility
0            0
1            1
2            0
3            0
4            0
5            1
6            0
7            0
8            1
9            0

# K-means Clustering

In [373]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

def k_means_clustering(data, num):
    scaler = StandardScaler()
    model = KMeans(init="k-means++", n_clusters=num, random_state=42)
    pipeline = make_pipeline(scaler, model)
    pipeline.fit(data)
    predict_class = pd.DataFrame(pipeline.predict(data))
    predict_class.columns = ['class']
    return predict_class

def create_cross_table(y, predict_class):
    cross_table = pd.crosstab(y['Credibility'], predict_class['class'])
    cross_table.loc['total'] = cross_table.select_dtypes(pd.np.number).sum()
    cross_table.iloc[0] = cross_table.iloc[0] / cross_table.iloc[2]
    cross_table.iloc[1] = cross_table.iloc[1] / cross_table.iloc[2]
    
    # over 60 detect
    list_class = []
    list_credible = []

    for i in range(2): # credible
        for j in range(len(cross_table.iloc[i])): # class
            if cross_table.iloc[i][j] >= 0.6:
                list_credible.append(i)
                list_class.append(j)

    over60_zip = list(zip(list_class, list_credible))
    over60_zip.sort(key = lambda x: x[0])
    print ("한 쪽이 60% 넘는 총 개수는 {0} 개".format(len(over60_zip)))
    for i in range(len(over60_zip)):
        print ("60%가 넘는 것은 class: {0}, credibility: {1} 일 때 입니다. ".format(over60_zip[i][0], over60_zip[i][1]))
    
    return cross_table

In [374]:
predict_feature_all_4 = k_means_clustering(x, 4)
ct4 = create_cross_table(y, predict_feature_all_4)
ct4

한 쪽이 60% 넘는 총 개수는 2 개
60%가 넘는 것은 class: 0, credibility: 1 일 때 입니다.
60%가 넘는 것은 class: 2, credibility: 0 일 때 입니다.

class                  0           1    2            3
Credibility
0               0.286633     0.53347  1.0     0.508239
1               0.713367     0.46653  0.0     0.491761
total        1399.000000  8291.00000  4.0  2306.000000

In [375]:
predict_feature_all_5 = k_means_clustering(x, 5)
ct5 = create_cross_table(y, predict_feature_all_5)
ct5

한 쪽이 60% 넘는 총 개수는 4 개
60%가 넘는 것은 class: 0, credibility: 1 일 때 입니다.
60%가 넘는 것은 class: 1, credibility: 1 일 때 입니다.
60%가 넘는 것은 class: 2, credibility: 0 일 때 입니다.
60%가 넘는 것은 class: 4, credibility: 0 일 때 입니다.

class                  0            1            2            3    4
Credibility
0               0.112989     0.320755     0.629452     0.563231  1.0
1               0.887011     0.679245     0.370548     0.436769  0.0
total        2071.000000  1166.000000  6879.000000  1882.000000  2.0

In [376]:
predict_feature_all_6 = k_means_clustering(x, 6)
ct6 = create_cross_table(y, predict_feature_all_6)
ct6

한 쪽이 60% 넘는 총 개수는 5 개
60%가 넘는 것은 class: 0, credibility: 1 일 때 입니다.
60%가 넘는 것은 class: 1, credibility: 1 일 때 입니다.
60%가 넘는 것은 class: 2, credibility: 0 일 때 입니다.
60%가 넘는 것은 class: 4, credibility: 0 일 때 입니다.
60%가 넘는 것은 class: 5, credibility: 0 일 때 입니다.

class                  0            1    2            3    4            5
Credibility
0               0.319828     0.113153  1.0     0.561105  1.0     0.629592
1               0.680172     0.886847  0.0     0.438895  0.0     0.370408
total        1160.000000  2068.000000  2.0  1882.000000  1.0  6887.000000

In [377]:
predict_feature_all_7 = k_means_clustering(x, 7)
ct7 = create_cross_table(y, predict_feature_all_7)
ct7

한 쪽이 60% 넘는 총 개수는 5 개
60%가 넘는 것은 class: 1, credibility: 1 일 때 입니다.
60%가 넘는 것은 class: 3, credibility: 1 일 때 입니다.
60%가 넘는 것은 class: 4, credibility: 0 일 때 입니다.
60%가 넘는 것은 class: 5, credibility: 0 일 때 입니다.
60%가 넘는 것은 class: 6, credibility: 1 일 때 입니다.

class,0,1,2,3,4,5,6
Credibility,,,,,,,
0,0.445499,0.138107,0.572124,0.390278,1.0,0.674205,0.303595
1,0.554501,0.861893,0.427876,0.609722,0.0,0.325795,0.696405
total,2633.000000,1564.000000,1643.000000,720.000000,2.0,4687.000000,751.000000

In [378]:
predict_feature_all_8 = k_means_clustering(x, 8)
ct8 = create_cross_table(y, predict_feature_all_8)
ct8

한 쪽이 60% 넘는 총 개수는 7 개
60%가 넘는 것은 class: 0, credibility: 1 일 때 입니다.
60%가 넘는 것은 class: 1, credibility: 1 일 때 입니다.
60%가 넘는 것은 class: 2, credibility: 0 일 때 입니다.
60%가 넘는 것은 class: 3, credibility: 0 일 때 입니다.
60%가 넘는 것은 class: 4, credibility: 1 일 때 입니다.
60%가 넘는 것은 class: 5, credibility: 0 일 때 입니다.
60%가 넘는 것은 class: 6, credibility: 0 일 때 입니다.

class,0,1,2,3,4,5,6,7
Credibility,,,,,,,,
0,0.113797,0.302667,1.0,1.0,0.381955,0.603978,0.621562,0.583333
1,0.886203,0.697333,0.0,0.0,0.618045,0.396022,0.378438,0.416667
total,1986.000000,750.000000,1.0,1.0,665.000000,1659.000000,6326.000000,612.000000

In [379]:
predict_feature_all_9 = k_means_clustering(x, 9)
ct9 = create_cross_table(y, predict_feature_all_9)
ct9

한 쪽이 60% 넘는 총 개수는 6 개
60%가 넘는 것은 class: 2, credibility: 0 일 때 입니다.
60%가 넘는 것은 class: 3, credibility: 1 일 때 입니다.
60%가 넘는 것은 class: 4, credibility: 1 일 때 입니다.
60%가 넘는 것은 class: 6, credibility: 1 일 때 입니다.
60%가 넘는 것은 class: 7, credibility: 0 일 때 입니다.
60%가 넘는 것은 class: 8, credibility: 0 일 때 입니다.

class,0,1,2,3,4,5,6,7,8
Credibility,,,,,,,,,
0,0.530565,0.569932,0.693769,0.033282,0.264507,0.400875,0.318508,1.0,1.0
1,0.469435,0.430068,0.306231,0.966718,0.735493,0.599125,0.681492,0.0,0.0
total,3010.000000,1623.000000,3948.000000,1292.000000,741.000000,686.000000,697.000000,2.0,1.0

In [381]:
predict_feature_all_10 = k_means_clustering(x, 10)
ct10 = create_cross_table(y, predict_feature_all_10)
ct10

한 쪽이 60% 넘는 총 개수는 7 개
60%가 넘는 것은 class: 0, credibility: 1 일 때 입니다.
60%가 넘는 것은 class: 1, credibility: 0 일 때 입니다.
60%가 넘는 것은 class: 3, credibility: 0 일 때 입니다.
60%가 넘는 것은 class: 5, credibility: 1 일 때 입니다.
60%가 넘는 것은 class: 7, credibility: 1 일 때 입니다.
60%가 넘는 것은 class: 8, credibility: 0 일 때 입니다.
60%가 넘는 것은 class: 9, credibility: 0 일 때 입니다.

class,0,1,2,3,4,5,6,7,8,9
Credibility,,,,,,,,,,
0,0.301205,0.682158,0.522903,1.0,0.59322,0.130869,0.58092,0.383792,1.0,1.0
1,0.698795,0.317842,0.477097,0.0,0.40678,0.869131,0.41908,0.616208,0.0,0.0
total,747.000000,3206.000000,3624.000000,1.0,1475.00000,1704.000000,587.00000,654.000000,1.0,1.0

In [382]:
predict_feature_all_11 = k_means_clustering(x, 11)
ct11 = create_cross_table(y, predict_feature_all_11)
ct11

한 쪽이 60% 넘는 총 개수는 8 개
60%가 넘는 것은 class: 0, credibility: 1 일 때 입니다.
60%가 넘는 것은 class: 2, credibility: 1 일 때 입니다.
60%가 넘는 것은 class: 3, credibility: 0 일 때 입니다.
60%가 넘는 것은 class: 6, credibility: 0 일 때 입니다.
60%가 넘는 것은 class: 7, credibility: 1 일 때 입니다.
60%가 넘는 것은 class: 8, credibility: 1 일 때 입니다.
60%가 넘는 것은 class: 9, credibility: 0 일 때 입니다.
60%가 넘는 것은 class: 10, credibility: 0 일 때 입니다.

class,0,1,2,3,4,5,6,7,8,9,10
Credibility,,,,,,,,,,,
0,0.263514,0.526934,0.033359,0.69088,0.581197,0.592186,1.0,0.391653,0.315407,1.0,1.0
1,0.736486,0.473066,0.966641,0.30912,0.418803,0.407814,0.0,0.608347,0.684593,0.0,0.0
total,740.000000,2896.000000,1289.000000,3717.00000,585.000000,1459.000000,1.0,623.000000,688.000000,1.0,1.0

In [383]:
predict_feature_all_12 = k_means_clustering(x, 12)
ct12 = create_cross_table(y, predict_feature_all_12)
ct12

한 쪽이 60% 넘는 총 개수는 9 개
60%가 넘는 것은 class: 1, credibility: 1 일 때 입니다.
60%가 넘는 것은 class: 2, credibility: 1 일 때 입니다.
60%가 넘는 것은 class: 3, credibility: 0 일 때 입니다.
60%가 넘는 것은 class: 5, credibility: 1 일 때 입니다.
60%가 넘는 것은 class: 6, credibility: 0 일 때 입니다.
60%가 넘는 것은 class: 7, credibility: 0 일 때 입니다.
60%가 넘는 것은 class: 9, credibility: 1 일 때 입니다.
60%가 넘는 것은 class: 10, credibility: 1 일 때 입니다.
60%가 넘는 것은 class: 11, credibility: 0 일 때 입니다.

class,0,1,2,3,4,5,6,7,8,9,10,11
Credibility,,,,,,,,,,,,
0,0.554054,0.265223,0.311143,1.0,0.59375,0.034188,1.0,0.694782,0.581197,0.39478,0.090909,1.0
1,0.445946,0.734777,0.688857,0.0,0.40625,0.965812,0.0,0.305218,0.418803,0.60522,0.909091,0.0
total,3552.000000,739.000000,691.000000,1.0,1472.00000,1287.000000,1.0,3047.000000,585.000000,613.00000,11.000000,1.0

In [384]:
predict_feature_all_13 = k_means_clustering(x, 13)
ct13 = create_cross_table(y, predict_feature_all_13)
ct13 # remove 3,7,9,10 / 13개

한 쪽이 60% 넘는 총 개수는 10 개
60%가 넘는 것은 class: 0, credibility: 1 일 때 입니다.
60%가 넘는 것은 class: 1, credibility: 1 일 때 입니다.
60%가 넘는 것은 class: 2, credibility: 1 일 때 입니다.
60%가 넘는 것은 class: 3, credibility: 0 일 때 입니다.
60%가 넘는 것은 class: 4, credibility: 1 일 때 입니다.
60%가 넘는 것은 class: 5, credibility: 0 일 때 입니다.
60%가 넘는 것은 class: 6, credibility: 1 일 때 입니다.
60%가 넘는 것은 class: 7, credibility: 0 일 때 입니다.
60%가 넘는 것은 class: 9, credibility: 0 일 때 입니다.
60%가 넘는 것은 class: 10, credibility: 1 일 때 입니다.

class,0,1,2,3,4,5,6,7,8,9,10,11,12
Credibility,,,,,,,,,,,,,
0,0.133333,0.033646,0.317251,1.0,0.393204,0.700764,0.269337,1.0,0.580479,1.0,0.0,0.536898,0.599442
1,0.866667,0.966354,0.682749,0.0,0.606796,0.299236,0.730663,0.0,0.419521,0.0,1.0,0.463102,0.400558
total,195.000000,1278.000000,684.000000,1.0,618.000000,3666.000000,724.000000,1.0,584.000000,1.0,10.0,2805.000000,1433.000000

In [385]:
predict_feature_all_14 = k_means_clustering(x, 14)
ct14 = create_cross_table(y, predict_feature_all_14)
ct14

한 쪽이 60% 넘는 총 개수는 9 개
60%가 넘는 것은 class: 2, credibility: 0 일 때 입니다.
60%가 넘는 것은 class: 3, credibility: 0 일 때 입니다.
60%가 넘는 것은 class: 4, credibility: 1 일 때 입니다.
60%가 넘는 것은 class: 5, credibility: 1 일 때 입니다.
60%가 넘는 것은 class: 8, credibility: 1 일 때 입니다.
60%가 넘는 것은 class: 9, credibility: 0 일 때 입니다.
60%가 넘는 것은 class: 11, credibility: 0 일 때 입니다.
60%가 넘는 것은 class: 12, credibility: 1 일 때 입니다.
60%가 넘는 것은 class: 13, credibility: 0 일 때 입니다.

class,0,1,2,3,4,5,6,7,8,9,10,11,12,13
Credibility,,,,,,,,,,,,,,
0,0.580205,0.555085,1.0,1.0,0.316401,0.033254,0.560065,0.5,0.390675,1.0,0.592998,1.0,0.255587,0.701178
1,0.419795,0.444915,0.0,0.0,0.683599,0.966746,0.439935,0.5,0.609325,0.0,0.407002,0.0,0.744413,0.298822
total,586.000000,3304.000000,1.0,1.0,689.000000,1263.000000,616.000000,28.0,622.000000,1.0,1371.000000,1.0,716.000000,2801.000000

# ct13 선택, 아직 편입은 미개발

In [387]:
df_clustering13_all = pd.concat([x, predict_feature_all_13], axis = 1)
df_clustering13_all.sample(5)

,Question_count,First_ratio,Second_ratio,Tag_count,pos_ratio,neg_ratio,subjectivity,polarity,senti_diffs_per_ref,Sticker_count,...,img img text img text,img text img img img,img text img img text,img text img text img,text img img img img,text img img img text,text img img text img,text img text img img,text img text img text,class
4070,3,0.000000,0.000000,5,0.027778,0.037037,0.064815,0.142857,-0.009259,2.0,...,0.325897,0.000000,0.315238,0.592377,0.0,0.000000,0.333817,0.296614,0.494057,12
10333,5,0.002725,0.000000,1,0.026316,0.046784,0.073099,0.280000,-0.020468,0.0,...,0.000000,0.000000,0.000000,0.693838,0.0,0.000000,0.000000,0.000000,0.720132,0
2758,0,0.000000,0.000000,9,0.017751,0.047337,0.065089,0.454545,-0.029586,0.0,...,0.000000,0.000000,0.157392,0.690111,0.0,0.000000,0.000000,0.148093,0.690683,11
10024,0,0.000000,0.001311,9,0.031447,0.037736,0.069182,0.090909,-0.006289,0.0,...,0.000000,0.000000,0.000000,0.650481,0.0,0.000000,0.000000,0.000000,0.759523,11
1249,2,0.004822,0.000964,7,0.049020,0.044118,0.093137,-0.052632,0.004902,1.0,...,0.145316,0.179495,0.281126,0.616323,0.0,0.213451,0.148848,0.264518,0.528714,4

In [391]:
# class 3,7,9,10 제거
print ("shape: ", df_clustering13_all.shape)
df_clustering13_remove4 = df_clustering13_all[df_clustering13_all['class'] != 3]
df_clustering13_remove4 = df_clustering13_remove4[df_clustering13_remove4['class'] != 7]
df_clustering13_remove4 = df_clustering13_remove4[df_clustering13_remove4['class'] != 9]
df_clustering13_remove4 = df_clustering13_remove4[df_clustering13_remove4['class'] != 10]
print ("shape: ", df_clustering13_remove4.shape)
df_clustering13_remove4.sample(10)

shape:  (12000, 32)
shape:  (11987, 32)

,Question_count,First_ratio,Second_ratio,Tag_count,pos_ratio,neg_ratio,subjectivity,polarity,senti_diffs_per_ref,Sticker_count,...,img img text img text,img text img img img,img text img img text,img text img text img,text img img img img,text img img img text,text img img text img,text img text img img,text img text img text,class
4495,1,0.001889,0.0,9,0.060811,0.058559,0.119369,-0.018868,0.002252,0.0,...,0.331047,0.000000,0.533699,0.468018,0.000000,0.000000,0.452123,0.301301,0.267661,12
2504,1,0.000000,0.0,9,0.028428,0.018395,0.046823,-0.214286,0.010033,0.0,...,0.185547,0.229188,0.179478,0.562109,0.000000,0.272545,0.380113,0.168875,0.450060,4
5226,0,0.001251,0.0,10,0.030369,0.017354,0.047722,-0.272727,0.013015,0.0,...,0.000000,0.000000,0.000000,0.686323,0.000000,0.000000,0.000000,0.000000,0.727297,5
10286,0,0.005319,0.0,3,0.047619,0.000000,0.047619,-1.000000,0.047619,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,5
4977,0,0.003165,0.0,7,0.000000,0.102941,0.102941,1.000000,-0.102941,0.0,...,0.000000,0.000000,0.038756,0.000000,0.054865,0.000000,0.000000,0.000000,0.000000,6
10639,1,0.000000,0.0,9,0.056940,0.053381,0.110320,-0.032258,0.003559,0.0,...,0.196905,0.243218,0.000000,0.119304,0.269629,0.000000,0.201691,0.179213,0.000000,6
10488,1,0.001963,0.0,9,0.026316,0.032164,0.058480,0.100000,-0.005848,0.0,...,0.038201,0.078643,0.000000,0.054007,0.069746,0.018704,0.000000,0.034768,0.030887,0
2044,2,0.000000,0.0,5,0.028249,0.028249,0.056497,0.000000,0.000000,6.0,...,0.095508,0.000000,0.092384,0.694412,0.000000,0.000000,0.097829,0.086926,0.694988,5
3607,0,0.004405,0.0,3,0.032967,0.043956,0.076923,0.142857,-0.010989,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,11
455,0,0.000000,0.0,5,0.015707,0.015707,0.031414,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.664056,0.000000,0.000000,0.000000,0.000000,0.747683,5

In [400]:
# ct8
df_clustering8_all = pd.concat([x, predict_feature_all_8], axis = 1)
df_clustering8_all.sample(5)

,Question_count,First_ratio,Second_ratio,Tag_count,pos_ratio,neg_ratio,subjectivity,polarity,senti_diffs_per_ref,Sticker_count,...,img img text img text,img text img img img,img text img img text,img text img text img,text img img img img,text img img img text,text img img text img,text img text img img,text img text img text,class
3416,0,0.0,0.0,9,1.000000e-09,1.000000e-09,1.000000e-09,1.000000e-09,1.000000e-09,0.0,...,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0
6747,2,0.0,0.0,0,3.015075e-02,3.517588e-02,6.532663e-02,7.692308e-02,-5.025126e-03,0.0,...,0.076655,0.0,0.222442,0.650223,0.0,0.0,0.235552,0.069767,0.650762,6
1631,0,0.0,0.0,5,2.371542e-02,1.976285e-02,4.347826e-02,-9.090909e-02,3.952569e-03,2.0,...,0.158472,0.0,0.153289,0.672119,0.0,0.0,0.162323,0.144232,0.672676,5
10259,0,0.0,0.0,1,2.782609e-02,2.608696e-02,5.391304e-02,-3.225806e-02,1.739130e-03,0.0,...,0.000000,0.0,0.000000,0.672368,0.0,0.0,0.000000,0.000000,0.740217,6
1937,1,0.0,0.0,3,4.687500e-02,1.041667e-02,5.729167e-02,-6.363636e-01,3.645833e-02,0.0,...,0.309691,0.0,0.299562,0.562919,0.0,0.0,0.317217,0.281864,0.563385,5

In [401]:
# class 2,3 제거
print ("shape: ", df_clustering8_all.shape)
df_clustering8_remove2 = df_clustering8_all[df_clustering8_all['class'] != 2]
df_clustering8_remove2 = df_clustering8_remove2[df_clustering8_remove2['class'] != 3]
print ("shape: ", df_clustering8_remove2.shape)
df_clustering8_remove2.sample(10)

shape:  (12000, 32)
shape:  (11998, 32)

,Question_count,First_ratio,Second_ratio,Tag_count,pos_ratio,neg_ratio,subjectivity,polarity,senti_diffs_per_ref,Sticker_count,...,img img text img text,img text img img img,img text img img text,img text img text img,text img img img img,text img img img text,text img img text img,text img text img img,text img text img text,class
2432,5,0.002024,0.0,3,4.166667e-02,3.921569e-02,8.088235e-02,-3.030303e-02,2.450980e-03,2.0,...,0.000000,0.000000,0.000000,0.672368,0.000000,0.00000,0.000000,0.000000,0.740217,6
4506,0,0.001399,0.0,0,2.362205e-02,2.362205e-02,4.724409e-02,0.000000e+00,0.000000e+00,1.0,...,0.000000,0.000000,0.157392,0.690111,0.000000,0.00000,0.000000,0.148093,0.690683,6
3747,0,0.000000,0.0,7,5.660377e-02,6.289308e-02,1.194969e-01,5.263158e-02,-6.289308e-03,0.0,...,0.000000,0.000000,0.000000,0.672368,0.000000,0.00000,0.000000,0.000000,0.740217,6
9864,2,0.000518,0.0,8,4.422254e-02,4.279601e-02,8.701854e-02,-1.639344e-02,1.426534e-03,0.0,...,0.216308,0.356246,0.209233,0.480553,0.098733,0.31773,0.221565,0.262496,0.306060,4
6048,0,0.006757,0.0,7,9.452736e-02,6.965174e-02,1.641791e-01,-1.515152e-01,2.487562e-02,0.0,...,0.000000,0.000000,0.000000,0.695849,0.000000,0.00000,0.000000,0.000000,0.718189,6
8596,0,0.000902,0.0,0,4.184100e-02,2.928870e-02,7.112971e-02,-1.764706e-01,1.255230e-02,0.0,...,0.000000,0.000000,0.000000,0.639871,0.000000,0.00000,0.000000,0.000000,0.768482,6
4768,1,0.003130,0.0,0,1.739130e-02,4.347826e-02,6.086957e-02,4.285714e-01,-2.608696e-02,0.0,...,0.339763,0.000000,0.000000,0.617580,0.000000,0.00000,0.348020,0.000000,0.618092,5
7925,1,0.000881,0.0,2,3.404255e-02,3.829787e-02,7.234043e-02,5.882353e-02,-4.255319e-03,0.0,...,0.000000,0.000000,0.000000,0.599682,0.000000,0.00000,0.000000,0.000000,0.800238,6
6816,0,0.000000,0.0,3,1.000000e-09,1.000000e-09,1.000000e-09,1.000000e-09,1.000000e-09,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0
7268,0,0.000811,0.0,10,4.090909e-02,2.272727e-02,6.363636e-02,-2.857143e-01,1.818182e-02,2.0,...,0.178134,0.000000,0.344616,0.647583,0.000000,0.00000,0.182464,0.324257,0.540100,5

# structure, sentiment, other

In [393]:
# structure data
structure_features = ['img img img img img', 'img img img img text', 'img img img text img',
                      'img img text img img', 'img img text img text', 'img text img img img',
                      'img text img img text', 'img text img text img', 'text img img img img',
                      'text img img img text', 'text img img text img', 'text img text img img', 
                      'text img text img text', 'class'] # total 13, class 제외

df_structure = df_clustering8_remove2[structure_features]
print ("shape: ", df_structure.shape)
df_structure.sample(10)

shape:  (11987, 14)

,img img img img img,img img img img text,img img img text img,img img text img img,img img text img text,img text img img img,img text img img text,img text img text img,text img img img img,text img img img text,text img img text img,text img text img img,text img text img text,class
1458,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.599682,0.0,0.000000,0.000000,0.000000,0.800238,11
536,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,1
8545,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.639871,0.0,0.000000,0.000000,0.000000,0.768482,11
8550,0.0,0.0,0.0,0.0,0.000000,0.258219,0.000000,0.633311,0.0,0.307069,0.000000,0.190266,0.633836,11
7993,0.0,0.0,0.0,0.0,0.221202,0.000000,0.213968,0.670126,0.0,0.000000,0.226578,0.201327,0.603613,12
2192,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.664056,0.0,0.000000,0.000000,0.000000,0.747683,11
3140,0.0,0.0,0.0,0.0,0.000000,0.000000,0.157392,0.690111,0.0,0.000000,0.000000,0.148093,0.690683,5
3261,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,1
9786,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.650481,0.0,0.000000,0.000000,0.000000,0.759523,5
11820,0.0,0.0,0.0,0.0,0.253425,0.000000,0.245137,0.614196,0.0,0.000000,0.259584,0.230654,0.614705,12

In [402]:
# save strucuture data
# df_structure.to_csv("data/df_structure8_sampling.csv", header = True, index = False)

In [403]:
# sentiment data
sentiment_features = ['pos_ratio', 'neg_ratio', 'subjectivity', 'polarity', 'senti_diffs_per_ref', 'class']
df_sentiment = df_clustering8_remove2[sentiment_features]
print ("shape: ", df_sentiment.shape)
df_sentiment.sample(10)

shape:  (11998, 6)

,pos_ratio,neg_ratio,subjectivity,polarity,senti_diffs_per_ref,class
7822,0.036082,0.030928,0.067010,-7.692308e-02,0.005155,6
10687,0.035019,0.023346,0.058366,-2.000000e-01,0.011673,6
77,0.032641,0.059347,0.091988,2.903226e-01,-0.026706,0
4207,0.025253,0.040404,0.065657,2.307692e-01,-0.015152,7
7583,0.042773,0.069322,0.112094,2.368421e-01,-0.026549,5
2118,0.008130,0.032520,0.040650,6.000000e-01,-0.024390,6
9868,0.037383,0.037383,0.074766,0.000000e+00,0.000000,7
9666,0.037037,0.064815,0.101852,2.727273e-01,-0.027778,6
11729,0.000000,0.000000,0.000000,1.000000e-09,0.000000,1
10111,0.077640,0.027950,0.105590,-4.705882e-01,0.049689,1

In [404]:
# save sentiment data
df_sentiment.to_csv("data/df_sentiment8_sampling.csv", header = True, index = False)

In [405]:
# others
others_features = ['Tag_count', 'First_ratio', 'Second_ratio', 'Sticker_count', 'Text_len', 'effort_img_ratio',
                   'Count_space_mistake', 'effort_ratio', 'Left', 'Center', 'Right', 'Justify', 'Question_count', 'class']

df_others = df_clustering8_remove2[others_features]
print ("shape: ", df_others.shape)
df_others.sample(10)

shape:  (11998, 14)

,Tag_count,First_ratio,Second_ratio,Sticker_count,Text_len,effort_img_ratio,Count_space_mistake,effort_ratio,Left,Center,Right,Justify,Question_count,class
4670,2,0.000000,0.001689,0.0,592.0,0.382571,7.0,0.773912,0.0,0.0,0.0,0.0,2,6
6065,10,0.000785,0.000000,0.0,1274.0,0.592401,53.0,1.022735,0.0,9.0,0.0,4.0,0,6
4030,0,0.002436,0.000000,0.0,1642.0,0.000000,52.0,1.270806,0.0,0.0,0.0,78.0,7,0
6224,8,0.001275,0.000000,0.0,4705.0,2.918425,99.0,2.893370,0.0,0.0,0.0,0.0,1,6
6263,0,0.000000,0.000000,0.0,717.0,0.590639,42.0,0.519291,0.0,15.0,0.0,0.0,2,6
11450,10,0.000000,0.000000,0.0,893.0,0.614144,28.0,0.702713,0.0,55.0,0.0,0.0,1,6
9818,0,0.000000,0.000000,0.0,556.0,0.609398,45.0,0.411370,0.0,16.0,0.0,0.0,0,6
11004,4,0.002191,0.000000,0.0,2282.0,0.261171,55.0,1.688394,7.0,0.0,0.0,3.0,0,6
7823,0,0.000000,0.000000,0.0,1438.0,0.716598,63.0,0.979039,0.0,39.0,0.0,0.0,1,6
6262,10,0.002519,0.000840,5.0,1191.0,1.353574,31.0,0.810873,0.0,34.0,0.0,0.0,8,7

In [406]:
# save others data
df_others.to_csv("data/df_others8_sampling.csv", header = True, index = False)

# end 10/29, 01:00

In [171]:
features10_temp = features10.copy()
features10_temp.append('class')
features10_temp

['Left',
 'neg_ratio',
 'Justify',
 'text img text img text',
 'Count_space_mistake',
 'img text img text img',
 'effort_ratio',
 'Text_len',
 'effort_img_ratio',
 'Center',
 'class']

In [138]:
df_clustering_all_select10 = df_clustering_all[features10_temp]
print ("shape: ", df_clustering_all_select10.shape)
df_clustering_all_select10.sample(5)

shape:  (16213, 15)

,Left,neg_ratio,Justify,text img text img text,Count_space_mistake,img text img text img,effort_ratio,Text_len,effort_img_ratio,Center,class,class,class,class,class
12997,0.0,0.057072,0.0,0.000000,48.0,0.000000,2.397896,3522.0,1.592440,3.0,0,0,0,0,0
12663,0.0,0.016667,3.0,0.497686,20.0,0.596729,0.624454,844.0,1.131740,17.0,4,4,4,4,4
7193,0.0,0.025641,0.0,0.147281,36.0,0.147159,0.400008,617.0,0.644624,20.0,4,4,4,4,4
12238,0.0,0.038462,0.0,0.643737,64.0,0.643204,0.945877,1306.0,0.885958,131.0,1,1,1,1,1
9862,11.0,0.050239,26.0,0.000000,23.0,0.000000,1.083553,1762.0,1.497613,3.0,0,0,0,0,0

In [127]:
# save data
# df_clustering_all.to_csv('data/clustering_all.csv', header=True, index=False)
# df_clustering_all_select10.to_csv('data/clustering_all_select10.csv', header=True, index=False)

# radviz

In [167]:
# 10개 변수로 clustering
features10 = ['Left', 'neg_ratio', 'Justify', 'text img text img text', 'Count_space_mistake',
              'img text img text img', 'effort_ratio', 'Text_len', 'effort_img_ratio', 'Center']

df_features10_x = x[features10]
print (df_features10_x.shape)
df_features10_x.head(10)

(16213, 10)

,Left,neg_ratio,Justify,text img text img text,Count_space_mistake,img text img text img,effort_ratio,Text_len,effort_img_ratio,Center
0,0.0,5.329154e-02,11.0,0.317769,32.0,0.317506,1.051315e+00,1336.00000,0.750620,9.0
1,0.0,1.020408e-01,0.0,0.230560,11.0,0.230369,2.392180e-01,389.00000,0.230402,42.0
2,1.0,2.072539e-02,0.0,0.700485,57.0,0.699905,1.997661e+00,2700.00000,1.218797,161.0
3,27.0,5.490196e-02,12.0,0.401655,59.0,0.561851,8.175207e-01,1261.00000,0.687599,0.0
4,0.0,4.697987e-02,0.0,0.614705,28.0,0.614196,1.256182e+00,1308.00000,1.062837,10.0
5,15.0,2.090592e-02,6.0,0.324336,39.0,0.432089,1.022648e+00,1412.00000,1.279717,0.0
6,0.0,5.394191e-02,12.0,0.374921,44.0,0.468264,1.543922e+00,1962.00000,0.887097,13.0
7,0.0,1.619433e-02,6.0,0.184331,10.0,0.245571,7.610793e-01,1021.00000,1.008649,15.0
8,0.0,1.000000e-09,24.0,0.000000,0.0,0.000000,7.454254e-09,0.00001,1.274083,2.0
9,0.0,3.108808e-02,0.0,0.722928,49.0,0.690924,5.603552e-01,977.00000,2.704520,70.0

In [78]:
# 10개 변수로 clustering
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

scaler = StandardScaler()
feature10_model = KMeans(n_clusters=5)
pipeline = make_pipeline(scaler,feature10_model)
pipeline.fit(df_features10_x)
predict_feature10 = pd.DataFrame(pipeline.predict(df_features10_x))

In [79]:
predict_feature10.columns = ['class']
predict_feature10

       class
0          2
1          2
2          3
3          2
4          3
5          3
6          2
7          2
8          3
9          3
10         3
11         2
12         2
13         2
14         2
15         2
16         2
17         0
18         3
19         2
20         2
21         2
22         3
23         2
24         2
25         2
26         2
27         2
28         2
29         2
...      ...
16183      2
16184      0
16185      2
16186      2
16187      3
16188      2
16189      3
16190      2
16191      3
16192      2
16193      3
16194      3
16195      2
16196      2
16197      3
16198      2
16199      2
16200      2
16201      2
16202      3
16203      2
16204      2
16205      3
16206      2
16207      2
16208      2
16209      2
16210      2
16211      3
16212      2

[16213 rows x 1 columns]

In [80]:
ct10 = pd.crosstab(y['Credibility'], predict_feature10['class'])
ct10.loc['total'] = ct10.select_dtypes(pd.np.number).sum()
ct10.iloc [0] = ct10.iloc[0] / ct10.iloc[2]
ct10.iloc [1] = ct10.iloc[1] / ct10.iloc[2]
ct10

class                 0    1             2            3    4
Credibility
0              0.394834  0.0      0.387016     0.389037  1.0
1              0.605166  1.0      0.612984     0.610963  0.0
total        542.000000  3.0  10413.000000  5254.000000  1.0

In [81]:
cluster_data10 = pd.concat([x,predict_feature10], axis=1)
print ("shape: ", cluster_data10.shape)
cluster_data10

shape:  (16213, 32)

,Question_count,First_ratio,Second_ratio,Tag_count,pos_ratio,neg_ratio,subjectivity,polarity,senti_diffs_per_ref,Sticker_count,...,img img text img text,img text img img img,img text img img text,img text img text img,text img img img img,text img img img text,text img img text img,text img text img img,text img text img text,class
0,1,0.000192,0.000000,0,3.498542e-02,3.109815e-02,6.608358e-02,-5.882353e-02,3.887269e-03,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2
1,0,0.000537,0.000000,6,3.432494e-02,4.118993e-02,7.551487e-02,9.090909e-02,-6.864989e-03,0.0,...,0.000000,0.000000,0.000000,0.690176,0.000000,0.000000,0.000000,0.000000,0.723641,2
2,2,0.009901,0.000000,9,2.564103e-02,7.692308e-02,1.025641e-01,5.000000e-01,-5.128205e-02,0.0,...,0.000000,0.000000,0.000000,0.599682,0.000000,0.000000,0.000000,0.000000,0.800238,3
3,3,0.000943,0.003774,10,5.579399e-02,3.862661e-02,9.442060e-02,-1.818182e-01,1.716738e-02,0.0,...,0.000000,0.000000,0.000000,0.599682,0.000000,0.000000,0.000000,0.000000,0.800238,2
4,0,0.000000,0.000000,0,4.945055e-02,2.197802e-02,7.142857e-02,-3.846154e-01,2.747253e-02,0.0,...,0.000000,0.000000,0.182095,0.684364,0.000000,0.000000,0.000000,0.171337,0.684931,3
5,0,0.000763,0.000000,7,4.006678e-02,5.175292e-02,9.181970e-02,1.272727e-01,-1.168614e-02,0.0,...,0.237788,0.000000,0.262870,0.679208,0.000000,0.000000,0.278362,0.216422,0.535577,3
6,5,0.002273,0.000000,2,2.631579e-02,1.973684e-02,4.605263e-02,-1.428571e-01,6.578947e-03,0.0,...,0.000000,0.000000,0.000000,0.650481,0.000000,0.000000,0.000000,0.000000,0.759523,2
7,1,0.000000,0.000000,8,8.108108e-02,6.756757e-03,8.783784e-02,-8.461538e-01,7.432432e-02,0.0,...,0.000000,0.000000,0.000000,0.675420,0.000000,0.000000,0.000000,0.000000,0.737433,2
8,0,0.000000,0.000000,7,1.818182e-02,0.000000e+00,1.818182e-02,-1.000000e+00,1.818182e-02,0.0,...,0.000000,0.076096,0.000000,0.000000,0.084360,0.000000,0.063104,0.000000,0.000000,3
9,0,0.000000,0.000000,4,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e-09,0.000000e+00,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3
10,0,0.000000,0.000000,1,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e-09,0.000000e+00,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,3
11,3,0.003641,0.000000,5,3.246753e-02,1.298701e-02,4.545455e-02,-4.285714e-01,1.948052e-02,0.0,...,0.000000,0.000000,0.000000,0.624379,0.000000,0.000000,0.000000,0.000000,0.781121,2
12,9,0.004199,0.000000,10,3.634827e-02,5.325444e-02,8.960270e-02,1.886792e-01,-1.690617e-02,0.0,...,0.266255,0.000000,0.515093,0.161322,0.000000,0.000000,0.636359,0.161554,0.053819,2
13,1,0.009772,0.000000,5,3.521127e-02,9.154930e-02,1.267606e-01,4.444444e-01,-5.633803e-02,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2
14,0,0.000000,0.000000,5,2.678571e-02,1.785714e-02,4.464286e-02,-2.000000e-01,8.928571e-03,0.0,...,0.354208,0.437519,0.000000,0.214612,0.000000,0.520288,0.000000,0.322381,0.214790,2
15,1,0.013649,0.000000,4,3.594771e-02,3.594771e-02,7.189542e-02,0.000000e+00,0.000000e+00,0.0,...,0.000000,0.000000,0.000000,0.624379,0.000000,0.000000,0.000000,0.000000,0.781121,2
16,1,0.001409,0.000000,6,4.778157e-02,1.706485e-02,6.484642e-02,-4.736842e-01,3.071672e-02,0.0,...,0.181768,0.000000,0.175822,0.660791,0.000000,0.000000,0.186185,0.165435,0.661339,2
17,2,0.000000,0.000000,10,5.217391e-02,4.347826e-02,9.565217e-02,-9.090909e-02,8.695652e-03,0.0,...,0.000000,0.000000,0.157392,0.690111,0.000000,0.000000,0.000000,0.148093,0.690683,0
18,0,0.000000,0.000000,7,5.405405e-02,3.378378e-02,8.783784e-02,-2.307692e-01,2.027027e-02,0.0,...,0.404590,0.000000,0.391357,0.490277,0.000000,0.000000,0.414422,0.368236,0.368012,3
19,0,0.000000,0.000000,1,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e-09,0.000000e+00,0.0,...,0.023552,0.029091,0.000000,0.042810,0.032250,0.000000,0.000000,0.021436,0.028563,2
20,0,0.000000,0.000000,1,5.882353e-02,7.352941e-02,1.323529e-01,1.111111e-01,-1.470588e-02,0.0,...,0.000000,0.000000,0.000000,0.639871,0.000000,0.000000,0.000000,0.000000,0.768482,2
21,0,0.000000,0.000000,0,1.000000e-09,1.000000e-09,1.000000e-09,1.000000e-09,1.000000e-09,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2
22,3,0.000000,0.000000,3,2.868852e-03,1.762295e-02,2.049180e-02,7.200000e-01,-1.475410e-02,0.0,...,0.000000,0.000000,0.000000,0.554382,0.000000,0.000000,0.000000,0.000000,0.832262,3
23,2,0.000046,0.000000,1,0.000000e+00,1.276053e-03,1.276053e-03,1.000000e+00,-1.276053e-03,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2
24,1,0.000000,0.000000,2,3.750000e-02,3.125000e-02,6.875000e-02,-9.090909e-02,6.250000e-03,0.0,...,0.212316,0.000000,0.205371,0.643204,0.000000,0.000000,0.217476,0.193238,0.643737,2
25,11,0.000920,0.000000,0,7.089552e-02,8.955224e-02,1.604478e-01,1.162791e-01,-1.865672e-02,0.0,...,0.000000,0.000000,0.000000,0.658196,0.000000,0.000000,0.000000,0.000000,0.752847,2
26,0,0.000000,0.000000,3,2.777778e-02,5.555556e-02,8.333333e-02,3.333333e-01,-2.777778e-02,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2
27,0,0.002073,0.000000,6,4.905660e-02,2.641509e-02,7.547170e-02,-3.000000e-01,2.264151e-02,9.0,...,0.069336,0.000000,0.536547,0.042010,0.000000,0.000000,0.568170,0.000000,0.042045,2
28,4,0.000000,0.000000,6,3.424658e-02,1.369863e-02,4.794521e-02,-4.285714e-01,2.054795e-02,2.0,...,0.000000,0.000000,0.000000,0.664056,0.000000,0.000000,0.000000,0.000000,0.747683,2
29,1,0.000000,0.000000,10,5.759162e-02,3.141361e-02,8.900524e-02,-2.941176e-01,2.617801e-02,5.0,...,0.203653,0.000000,0.196992,0.678657,0.000000,0.000000,0.208603,0.185354,0.617473,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16183,0,0.000000,0.000000,10,4.411765e-02,1.470588e-02,5.882353e-02,-5.000000e-01,2.941176e-02,0.0,...,0.000000,0.000000,0.000000,0.706814,0.000000,0.000000,0.000000,0.000000,0.707400,2
16184,3,0.000587,0.001174,10,3.875969e-02,5.943152e-02,9.819121e-02,2.105263e-01,-2.067183e-02,1.0,...,0.000000,0.000000,0.182095,0.684364,0.000000,0.000000,0.000000,0.171337,0.684931,0
16185,0,0.000000,0.000000,0,1.000000e-09,1.000000e-09,1.000000e-09,1.000000e-09,1.000000e-09,0.0,...,0.000000,0.000000,0.000000,0.000000,0.037527,0.000000,0.000000,0.000000,0.000000,2
16186,7,0.003161,0.000000,4,6.647399e-02,2.023121e-02,8.670520e-02,-5.333333e-01,4.624277e-02,1.0,...,0.000000,0.000000,0.080112,0.702525,0.000000,0.000000,0.000000,0.075379,0.703107,2
16187,0,0.000000,0.000000,0,1.000000e-09,1.000000e-09,1.000000e-09,1.000000e-09,1.000000e-09,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3
16188,2,0.003861,0.000000,8,4.000000e-02,4.666667e-02,8.666667e-02,7.692308e-02,-6.666667e-03,0.0,...,0.000000,0.000000,0.000000,0.658196,0.000000,0.000000,0.000000,0.000000,0.752847,2
16189,0,0.000000,0.000000,0,1.562500e-02,3.125000e-02,4.687500e-02,3.333333e-01,-1.562500e-02,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3
16190,0,0.000000,0.000000,1,1.000000e-09,1.000000e-09,1.000000e-09,1.000000e-09,1.000000e-09,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2
16191,0,0.000000,0.000000,8,4.929577e-02,5.633803e-02,1.056338e-01,6.666667e-02,-7.042254e-03,0.0,...,0.000000,0.000000,0.000000,0.677977,0.000000,0.000000,0.000000,0.000000,0.735083,3
16192,1,0.000382,0.000000,10,8.396947e-02,5.343511e-02,1.374046e-01,-2.222222e-01,3.053435e-02,0.0,...,0.000000,0.000000,0.000000,0.000000,0.184541,0.000000,0.000000,0.000000,0.000000,2
16193,1,0.000000,0.000000,10,2.358491e-02,4.716981e-02,7.075472e-02,3.333333e-01,-2.358491e-02,2.0,...,0.000000,0.116717,0.000000,0.687028,0.129392,0.000000,0.000000,0.086002,0.687597,3
16194,1,0.001661,0.000000,0,5.185185e-02,5.925926e-02,1.111111e-01,6.666667e-02,-7.407407e-03,0.0,...,0.000000,0.000000,0.000000,0.694297,0.000000,0.000000,0.000000,0.000000,0.719689,3
16195,1,0.000000,0.000000,0,4.926108e-02,1.477833e-02,6.403941e-02,-5.384615e-01,3.448276e-02,0.0,...,0.140246,0.000000,0.135659,0.679791,0.000000,0.000000,0.143654,0.127644,0.680355,2
16196,0,0.002161,0.000000,4,9.966777e-03,3.322259e-02,4.318937e-02,5.384615e-01,-2.325581e-02,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2
16197,3,0.000000,0.000000,10,4.458599e-02,7.643312e-02,1.210191e-01,2.631579e-01,-3.184713e-02,0.0,...,0.000000,0.000000,0.157392,0.690111,0.000000,0.000000,0.000000,0.148093,0.690683,3
16198,0,0.002571,0.000000,6,1.250000e-02,5.000000e-02,6.250000e-02,6.000000e-01,-3.750000e-02,0.0,...,0.000000,0.000000,0.000000,0.691607,0.000000,0.000000,0.000000,0.000000,0.722274,2
16199,3,0.000000,0.000000,10,4.318937e-02,1.993355e-02,6.312292e-02,-3.684211e-01,2.325581e-02,0.0,...,0.137533,0.000000,0.532139,0.041665,0.000000,0.000000,0.563502,0.062588,0.000000,2
16200,5,0.003676,0.000000,10,7.829978e-02,7.270694e-02,1.510067e-01,-3.703704e-02,5.592841e-03,0.0,...,0.088954,0.000000,0.172089,0.700657,0.000000,0.000000,0.182232,0.080961,0.647296,2
16201,1,0.000823,0.000000,4,4.609929e-02,3.546099e-02,8.156028e-02,-1.304348e-01,1.063830e-02,0.0,...,0.083565,0.000000,0.161664,0.708842,0.000000,0.000000,0.085596,0.152113,0.658756,2
16202,3,0.000000,0.000000,6,8.968610e-03,2.242152e-02,3.139013e-02,4.285714e-01,-1.345291e-02,0.0,...,0.000000,0.000000,0.000000,0.706814,0.000000,0.000000,0.000000,0.000000,0.707400,3
16203,2,0.001067,0.000000,6,3.061224e-02,2.551020e-02,5.612245e-02,-9.090909e-02,5.102041e-03,2.0,...,0.000000,0.000000,0.138478,0.693919,0.000000,0.000000,0.000000,0.130297,0.694494,2
16204,1,0.011799,0.002950,0,6.060606e-02,4.545455e-02,1.060606e-01,-1.428571e-01,1.515152e-02,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2
16205,0,0.000746,0.000000,5,2.183406e-02,1.310044e-02,3.493450e-02,-2.500000e-01,8.733624e-03,0.0,...,0.000000,0.000000,0.000000,0.599682,0.000000,0.000000,0.000000,0.000000,0.800238,3
16206,2,0.000945,0.000000,6,3.973510e-02,1.324503e-02,5.298013e-02,-5.000000e-01,2.649007e-02,2.0,...,0.292315,0.000000,0.282754,0.619891,0.000000,0.000000,0.449128,0.133025,0.443146,2
16207,0,0.001970,0.000000,1,4.615385e-02,2.564103e-02,7.179487e-02,-2.857143e-01,2.051282e-02,3.0,...,0.379732,0.000000,0.367312,0.575193,0.000000,0.000000,0.388960,0.345611,0.345402,2
16208,0,0.002692,0.000000,0,1.104651e-01,5.232558e-02,1.627907e-01,-3.571429e-01,5.813953e-02,0.0,...,0.269129,0.000000,0.000000,0.652254,0.000000,0.000000,0.275669,0.000000,0.652795,2
16209,5,0.002072,0.001381,5,1.880878e-02,1.253918e-02,3.134796e-02,-2.000000e-01,6.269592e-03,0.0,...,0.000000,0.000000,0.564154,0.212025,0.000000,0.000000,0.477923,0.106165,0.212201,2
16210,0,0.003764,0.000000,0,3.267974e-02,6.535948e-03,3.921569e-02,-6.666667e-01,2.614379e-02,0.0,...,0.206634,0.085078,0.533003,0.125198,0.000000,0.101173,0.564417,0.188068,0.041767,2
16211,1,0.000717,0.000000,10,3.323263e-02,6.948640e-02,1.027190e-01,3.529412e-01,-3.625378e-02,0.0,...,0.193440,0.159291,0.249484,0.625087,0.000000,0.189426,0.264188,0.176058,0.508304,3
16212,0,0.007788,0.000000,2,4.703833e-02,5.574913e-02,1.027875e-01,8.474576e-02,-8.710801e-03,0.0,...,0.000000,0.000000,0.000000,0.639871,0.000000,0.000000,0.000000,0.000000,0.768482,2

In [ ]:
# save data

# end

In [ ]:
predict.columns = ['predict']

In [ ]:
y = y.reset_index(drop=True)

In [ ]:
ct = pd.crosstab(y['Credibility'],predict['predict'])

In [ ]:
ct.loc['total'] = ct.select_dtypes(pd.np.number).sum()

In [ ]:
ct

In [ ]:
ct.iloc [0] = ct.iloc[0] / ct.iloc[2]
ct.iloc [1] = ct.iloc[1] / ct.iloc[2]
ct

In [ ]:
ks = range(1,30)

inertias = []

for k in ks:
    model = KMeans(n_clusters=k)
    model.fit(x)
    inertias.append(model.inertia_)

# Plot ks vs inertias
plt.plot(ks, inertias, '-o')
plt.xlabel('number of clusters, k')
plt.ylabel('inertia')
plt.xticks(ks)
plt.show()

# 각 Group 비교하기

## Standard scaler

In [ ]:
col_name = x.columns.tolist()
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x)
scaled_x = scaler.transform(x)
scaled_x_df = pd.DataFrame(scaled_x)
scaled_x_df.columns = col_name
scaled_x_df

In [ ]:
scaled_x_structure = scaled_x_df[['img img img img img',
 'img img img img text',
 'img img img text img',
 'img img text img img',
 'img img text img text',
 'img text img img img',
 'img text img img text',
 'img text img text img',
 'text img img img img',
 'text img img img text',
 'text img img text img',
 'text img text img img',
 'text img text img text']]

In [ ]:
df_analysis = pd.concat([scaled_x_structure,predict,y],axis=1)

In [ ]:
df_0 = df_analysis[df_analysis['predict']==0]
df_1 = df_analysis[df_analysis['predict']==1]
df_2 = df_analysis[df_analysis['predict']==2]
df_3 = df_analysis[df_analysis['predict']==3]
df_4 = df_analysis[df_analysis['predict']==4]
df_0

In [ ]:
df_0 = df_0.drop(columns=['Credibility','predict'])
df_1 = df_1.drop(columns=['Credibility','predict'])
df_2 = df_2.drop(columns=['Credibility','predict'])
df_3 = df_3.drop(columns=['Credibility','predict'])
df_4 = df_4.drop(columns=['Credibility','predict'])
df_0

# Python Radar chart - Structure

In [ ]:
import matplotlib.pyplot as plt
from math import pi

In [ ]:
df_0_mean = df_0.describe().iloc[1]
df_1_mean = df_1.describe().iloc[1]
df_2_mean = df_2.describe().iloc[1]
df_3_mean = df_3.describe().iloc[1]
df_0_mean

In [ ]:
df_0 = pd.DataFrame(df_0_mean).T
df_1 = pd.DataFrame(df_1_mean).T
df_2 = pd.DataFrame(df_2_mean).T
df_3 = pd.DataFrame(df_3_mean).T
df_0

In [ ]:
Total_df = pd.concat([df_0,df_1,df_2,df_3])
Total_df

In [ ]:
predict_col = pd.DataFrame({'predict':[1,2,3,4]})
Total_df['predict'] = [1,2,3,4]
Total_df

In [ ]:
import matplotlib.pyplot as plt
import pandas as pd
from math import pi
 
# ------- PART 1: Create background
 
# number of variable
categories=list(Total_df)[:-1]
print (categories)
N = len(categories)
 
# What will be the angle of each axis in the plot? (we divide the plot / number of variable)
angles = [n / float(N) * 2 * pi for n in range(N)]
print (angles)
angles += angles[:1]
 
# Initialise the spider plot
ax = plt.subplot(111, polar=True)
 
# If you want the first axis to be on top:
ax.set_theta_offset(pi / 2)
ax.set_theta_direction(-1)
 
# Draw one axe per variable + add labels labels yet
plt.xticks(angles[:-1], categories)
 
# Draw ylabels
ax.set_rlabel_position(0)
plt.yticks([-3,0,3], ["-3","0","3"], color="grey", size=7)
plt.ylim(-3,3)
 
 
# # ------- PART 2: Add plots
 
# Plot each individual = each line of the data
# I don't do a loop, because plotting more than 3 groups makes the chart unreadable
 
# Ind1
values = Total_df.iloc[0].drop('predict').values.flatten().tolist()
values += values[:1]
ax.plot(angles, values, linewidth=1, linestyle='solid', label="group A")
ax.fill(angles, values, 'b', alpha=0.1)
 
# Ind2
values= Total_df.iloc[1].drop('predict').values.flatten().tolist()
values += values[:1]
ax.plot(angles, values, linewidth=1, linestyle='solid', label="group B")
ax.fill(angles, values, 'r', alpha=0.1)

# Ind3
values= Total_df.iloc[2].drop('predict').values.flatten().tolist()
values += values[:1]
ax.plot(angles, values, linewidth=1, linestyle='solid', label="group B")
ax.fill(angles, values, 'c', alpha=0.1)

# Ind4
values= Total_df.iloc[3].drop('predict').values.flatten().tolist()
values += values[:1]
ax.plot(angles, values, linewidth=1, linestyle='solid', label="group B")
ax.fill(angles, values, 'm', alpha=0.1)

# Python Radar chart - Sentiment

In [ ]:
scaled_x_sentiment = scaled_x_df[['pos_ratio',
 'neg_ratio',
 'subjectivity',
 'polarity',
 'senti_diffs_per_ref',]]

In [ ]:
df_analysis = pd.concat([scaled_x_sentiment,predict,y],axis=1)

In [ ]:
df_0 = df_analysis[df_analysis['predict']==0]
df_1 = df_analysis[df_analysis['predict']==1]
df_2 = df_analysis[df_analysis['predict']==2]
df_3 = df_analysis[df_analysis['predict']==3]
df_4 = df_analysis[df_analysis['predict']==4]

In [ ]:
df_0 = df_0.drop(columns=['Credibility','predict'])
df_1 = df_1.drop(columns=['Credibility','predict'])
df_2 = df_2.drop(columns=['Credibility','predict'])
df_3 = df_3.drop(columns=['Credibility','predict'])
df_4 = df_4.drop(columns=['Credibility','predict'])

In [ ]:
import matplotlib.pyplot as plt
from math import pi

In [ ]:
df_0_mean = df_0.describe().iloc[1]
df_1_mean = df_1.describe().iloc[1]
df_2_mean = df_2.describe().iloc[1]
df_3_mean = df_3.describe().iloc[1]

In [ ]:
df_0 = pd.DataFrame(df_0_mean).T
df_1 = pd.DataFrame(df_1_mean).T
df_2 = pd.DataFrame(df_2_mean).T
df_3 = pd.DataFrame(df_3_mean).T

In [ ]:
Total_df = pd.concat([df_0,df_1,df_2,df_3])

In [ ]:
predict_col = pd.DataFrame({'predict':[1,2,3,4]})
Total_df['predict'] = [1,2,3,4]

In [ ]:
import matplotlib.pyplot as plt
import pandas as pd
from math import pi
 
# ------- PART 1: Create background
 
# number of variable
categories=list(Total_df)[:-1]
N = len(categories)
 
# What will be the angle of each axis in the plot? (we divide the plot / number of variable)
angles = [n / float(N) * 2 * pi for n in range(N)]
angles += angles[:1]
 
# Initialise the spider plot
ax = plt.subplot(111, polar=True)
 
# If you want the first axis to be on top:
ax.set_theta_offset(pi / 2)
ax.set_theta_direction(-1)
 
# Draw one axe per variable + add labels labels yet
plt.xticks(angles[:-1], categories)
 
# Draw ylabels
ax.set_rlabel_position(0)
plt.yticks([-0.2,0,0.2], ["-0.1","0","0.1"], color="grey", size=7)
plt.ylim(-0.2,0.2)
 
 
# # ------- PART 2: Add plots
 
# Plot each individual = each line of the data
# I don't do a loop, because plotting more than 3 groups makes the chart unreadable
 
# Ind1
values = Total_df.iloc[0].drop('predict').values.flatten().tolist()
values += values[:1]
ax.plot(angles, values, linewidth=1, linestyle='solid', label="group A")
ax.fill(angles, values, 'b', alpha=0.1)
 
# Ind2
values= Total_df.iloc[1].drop('predict').values.flatten().tolist()
values += values[:1]
ax.plot(angles, values, linewidth=1, linestyle='solid', label="group B")
ax.fill(angles, values, 'r', alpha=0.1)

# Ind3
values= Total_df.iloc[2].drop('predict').values.flatten().tolist()
values += values[:1]
ax.plot(angles, values, linewidth=1, linestyle='solid', label="group B")
ax.fill(angles, values, 'c', alpha=0.1)

# Ind4
values= Total_df.iloc[3].drop('predict').values.flatten().tolist()
values += values[:1]
ax.plot(angles, values, linewidth=1, linestyle='solid', label="group B")
ax.fill(angles, values, 'm', alpha=0.1)

# Python Radar chart - Others

In [ ]:
scaled_x_others = scaled_x_df[['FR_url',
 'Question_count',
 'First_ratio',
 'Second_ratio',
 'Tag_count',
'Sticker_count',
 'Text_len',
 'Count_space_mistake',
 'effort_ratio',
 'effort_img_ratio',
 'Left',
 'Center',
 'Right',
 'Justify']]

In [ ]:
df_analysis = pd.concat([scaled_x_others,predict,y],axis=1)

In [ ]:
df_0 = df_analysis[df_analysis['predict']==0]
df_1 = df_analysis[df_analysis['predict']==1]
df_2 = df_analysis[df_analysis['predict']==2]
df_3 = df_analysis[df_analysis['predict']==3]
df_4 = df_analysis[df_analysis['predict']==4]

In [ ]:
df_0 = df_0.drop(columns=['Credibility','predict'])
df_1 = df_1.drop(columns=['Credibility','predict'])
df_2 = df_2.drop(columns=['Credibility','predict'])
df_3 = df_3.drop(columns=['Credibility','predict'])
df_4 = df_4.drop(columns=['Credibility','predict'])

In [ ]:
import matplotlib.pyplot as plt
from math import pi

In [ ]:
df_0_mean = df_0.describe().iloc[1]
df_1_mean = df_1.describe().iloc[1]
df_2_mean = df_2.describe().iloc[1]
df_3_mean = df_3.describe().iloc[1]

In [ ]:
df_0 = pd.DataFrame(df_0_mean).T
df_1 = pd.DataFrame(df_1_mean).T
df_2 = pd.DataFrame(df_2_mean).T
df_3 = pd.DataFrame(df_3_mean).T

In [ ]:
Total_df = pd.concat([df_0,df_1,df_2,df_3])

In [ ]:
predict_col = pd.DataFrame({'predict':[1,2,3,4]})
Total_df['predict'] = [1,2,3,4]

In [ ]:
import matplotlib.pyplot as plt
import pandas as pd
from math import pi
 
# ------- PART 1: Create background
 
# number of variable
categories=list(Total_df)[:-1]
N = len(categories)
 
# What will be the angle of each axis in the plot? (we divide the plot / number of variable)
angles = [n / float(N) * 2 * pi for n in range(N)]
angles += angles[:1]
 
# Initialise the spider plot
ax = plt.subplot(111, polar=True)
 
# If you want the first axis to be on top:
ax.set_theta_offset(pi / 2)
ax.set_theta_direction(-1)
 
# Draw one axe per variable + add labels labels yet
plt.xticks(angles[:-1], categories)
 
# Draw ylabels
ax.set_rlabel_position(0)
plt.yticks([-0.5,0,5], ["-0.5","0","0.5"], color="grey", size=7)
plt.ylim(-0.5,0.5)
 
 
# # ------- PART 2: Add plots
 
# Plot each individual = each line of the data
# I don't do a loop, because plotting more than 3 groups makes the chart unreadable
 
# Ind1
values = Total_df.iloc[0].drop('predict').values.flatten().tolist()
values += values[:1]
ax.plot(angles, values, linewidth=1, linestyle='solid', label="group A")
ax.fill(angles, values, 'b', alpha=0.1)
 
# Ind2
values= Total_df.iloc[1].drop('predict').values.flatten().tolist()
values += values[:1]
ax.plot(angles, values, linewidth=1, linestyle='solid', label="group B")
ax.fill(angles, values, 'r', alpha=0.1)

# Ind3
values= Total_df.iloc[2].drop('predict').values.flatten().tolist()
values += values[:1]
ax.plot(angles, values, linewidth=1, linestyle='solid', label="group B")
ax.fill(angles, values, 'c', alpha=0.1)

# Ind4
values= Total_df.iloc[3].drop('predict').values.flatten().tolist()
values += values[:1]
ax.plot(angles, values, linewidth=1, linestyle='solid', label="group B")
ax.fill(angles, values, 'm', alpha=0.1)